version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /console
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /runtime
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /file-service
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /control_plane
    schedule: { interval: weekly }
