#!/usr/bin/env bash
set -euo pipefail

SANDBOX_KUBE_CONTEXT="${SANDBOX_KUBE_CONTEXT:-sandbox-local}"
TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/sandbox-secrets.XXXXXX")"
chmod 700 "$TEMP_DIR"

cleanup() {
  find "$TEMP_DIR" -type f -delete
  rmdir "$TEMP_DIR"
}
trap cleanup EXIT

umask 077

secret_exists() {
  kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace "$1" get secret "$2" >/dev/null 2>&1
}

if ! secret_exists sandbox-system sandbox-api-credentials; then
  openssl rand -hex 32 | tr -d '\n' >"$TEMP_DIR/control-plane-token"
  openssl rand -hex 32 | tr -d '\n' >"$TEMP_DIR/signing-key"
  openssl rand -hex 32 | tr -d '\n' >"$TEMP_DIR/workspace-id-key"
  kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system create secret generic sandbox-api-credentials \
    --from-file=control-plane-token="$TEMP_DIR/control-plane-token" \
    --from-file=signing-key="$TEMP_DIR/signing-key" \
    --from-file=workspace-id-key="$TEMP_DIR/workspace-id-key"
else
  if [ -z "$(kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system \
      get secret sandbox-api-credentials --output=jsonpath='{.data.control-plane-token}')" ]; then
    # One-release migration for clusters created before the component rename.
    # Copy the existing credential byte-for-byte; generating a replacement here
    # would invalidate every operator still using the current break-glass token.
    LEGACY_CONTROL_TOKEN_KEY="portal-token"
    kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system \
      get secret sandbox-api-credentials \
      --output="jsonpath={.data.${LEGACY_CONTROL_TOKEN_KEY}}" \
      >"$TEMP_DIR/control-plane-token.b64"
    if [ ! -s "$TEMP_DIR/control-plane-token.b64" ]; then
      echo "sandbox-api-credentials has neither the current nor previous control-plane token key" >&2
      exit 1
    fi
    printf '{"data":{"control-plane-token":"%s"}}' \
      "$(cat "$TEMP_DIR/control-plane-token.b64")" \
      >"$TEMP_DIR/control-plane-token.patch"
    kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system \
      patch secret sandbox-api-credentials --type=merge \
      --patch-file "$TEMP_DIR/control-plane-token.patch"
  fi

  if [ -z "$(kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system \
      get secret sandbox-api-credentials --output=jsonpath='{.data.workspace-id-key}')" ]; then
    # A secret from before workspace-id-key existed: Control Plane derived Workspace IDs
    # from signing-key back then, so the key must be a copy of signing-key, not a
    # fresh value - a fresh one would orphan every existing Workspace directory.
    # Patch in place: recreating the secret would rotate the other keys.
    kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system \
      get secret sandbox-api-credentials --output=jsonpath='{.data.signing-key}' >"$TEMP_DIR/workspace-id-key.b64"
    printf '{"data":{"workspace-id-key":"%s"}}' "$(cat "$TEMP_DIR/workspace-id-key.b64")" >"$TEMP_DIR/workspace-id-key.patch"
    kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system \
      patch secret sandbox-api-credentials --type=merge --patch-file "$TEMP_DIR/workspace-id-key.patch"
  fi
fi

if secret_exists sandbox-workloads sandbox-volume-auth; then
  kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-workloads \
    get secret sandbox-volume-auth --output=jsonpath='{.data.token}' \
    | base64 --decode >"$TEMP_DIR/volume-token"
elif secret_exists sandbox-system sandbox-volume-auth; then
  kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace sandbox-system \
    get secret sandbox-volume-auth --output=jsonpath='{.data.token}' \
    | base64 --decode >"$TEMP_DIR/volume-token"
else
  openssl rand -hex 32 | tr -d '\n' >"$TEMP_DIR/volume-token"
fi

for namespace in sandbox-workloads sandbox-system; do
  if ! secret_exists "$namespace" sandbox-volume-auth; then
    kubectl --context "$SANDBOX_KUBE_CONTEXT" --namespace "$namespace" create secret generic sandbox-volume-auth \
      --from-file=token="$TEMP_DIR/volume-token"
  fi
done

# Object-store credentials are generated by CephObjectStoreUser and copied by
# local-cluster.sh after RGW is Ready; bootstrap never invents an S3 identity.
